# optimize this source file even in debug builds, to make speed (esp. loading times) more bearable
# used for libs integrated here like stb_* and miniz(ip)

if ( CMAKE_MAJOR_VERSION LESS 3 OR ( CMAKE_MAJOR_VERSION EQUAL 3 AND CMAKE_MINOR_VERSION LESS 11 ) )
	function( always_optimize_sourcefile srcfilename )
		if( MSVC )
			set_source_files_properties( ${srcfilename} PROPERTIES COMPILE_FLAGS "/Ox" )
		else()
			set_source_files_properties( ${srcfilename} PROPERTIES COMPILE_FLAGS "-O2" )
		endif()
	endfunction()
else()
	function( always_optimize_sourcefile srcfilename )
		if( MSVC )
			set_source_files_properties( ${srcfilename} PROPERTIES COMPILE_OPTIONS "/Ox" )
		else()
			set_source_files_properties( ${srcfilename} PROPERTIES COMPILE_OPTIONS "-O2" )
		endif()
	endfunction()
endif()